server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        # 시작 페이지를 views/login.html로 지정합니다.
        index  views/login.html;
        try_files $uri $uri/ /views/login.html;
    }

    # 정적 파일(css, js) 경로 설정
    location /public/ {
        root /usr/share/nginx/html;
    }

    # views 폴더 내 html 접근 설정
    location /views/ {
        root /usr/share/nginx/html;
    }
}